### ISSUE TITLE
MongoDB issue

### ISSUE THREAD

**Issue by Jnss98b** [karafra/ai-art#26]
I just redeployed the bot with the latest commits and got this error immediately after. How do I remediate this?

`2022-08-26T05:19:52.089809+00:00 app[worker.1]: MongoError: Collection already exists. NS: test.Job
2022-08-26T05:19:52.089810+00:00 app[worker.1]:     at MessageStream.messageHandler (/app/node_modules/mongodb/lib/cmap/connection.js:299:20)
2022-08-26T05:19:52.089810+00:00 app[worker.1]:     at MessageStream.emit (node:events:513:28)
2022-08-26T05:19:52.089810+00:00 app[worker.1]:     at MessageStream.emit (node:domain:489:12)
2022-08-26T05:19:52.089811+00:00 app[worker.1]:     at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
2022-08-26T05:19:52.089811+00:00 app[worker.1]:     at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
2022-08-26T05:19:52.089811+00:00 app[worker.1]:     at writeOrBuffer (node:internal/streams/writable:391:12)
2022-08-26T05:19:52.089811+00:00 app[worker.1]:     at _write (node:internal/streams/writable:332:10)
2022-08-26T05:19:52.089812+00:00 app[worker.1]:     at MessageStream.Writable.write (node:internal/streams/writable:336:10)
2022-08-26T05:19:52.089812+00:00 app[worker.1]:     at TLSSocket.ondata (node:internal/streams/readable:754:22)
2022-08-26T05:19:52.089812+00:00 app[worker.1]:     at TLSSocket.emit (node:events:513:28)
2022-08-26T05:19:52.089813+00:00 app[worker.1]:     at TLSSocket.emit (node:domain:489:12)
2022-08-26T05:19:52.089813+00:00 app[worker.1]:     at addChunk (node:internal/streams/readable:315:12)
2022-08-26T05:19:52.089813+00:00 app[worker.1]:     at readableAddChunk (node:internal/streams/readable:289:9)
2022-08-26T05:19:52.089813+00:00 app[worker.1]:     at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
2022-08-26T05:19:52.089814+00:00 app[worker.1]:     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
2022-08-26T05:19:55.404560+00:00 app[worker.1]: [32m[Nest] 22  - [39m08/26/2022, 5:19:55 AM [32m    LOG[39m [38;5;3m[createCappedJobsCollection1661353047612] [39m[32mRunning migration Create capped Jobs collection 1661353047612[39m
2022-08-26T05:19:55.404785+00:00 app[worker.1]: [95m[Nest] 22  - [39m08/26/2022, 5:19:55 AM [95m  DEBUG[39m [38;5;3m[createCappedJobsCollection1661353047612] [39m[95mCreating capped collection "Jobs" with size 400000000B[39m
2022-08-26T05:19:55.440021+00:00 app[worker.1]: Migration "Create capped Jobs collection 1661353047612" failed, error: Collection already exists. NS: test.Job
2022-08-26T05:19:55.441449+00:00 app[worker.1]: [31m[Nest] 22  - [39m08/26/2022, 5:19:55 AM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (2)...[39m
`

**Comment by Jnss98b** [comment]
I still couldn't figure out what caused it but creating a new db fixed it
